version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: app-backend
    environment:
      - NODE_ENV=production
      - PORT=4000
    # Бэкенд не выставляем наружу — он только для фронта
    # ports:
    #   - "4000:4000"

  frontend:
    build:
      context: ./frontend
    container_name: app-frontend
    depends_on:
      - backend
    # В ПРОДЕ сразу вешаем на 80 порт сервера
    ports:
      - "80:3000"
